Finished equality functionality
EdiOancea/Calculator pull request #14
Opened 2019-03-07 10:55 UTC by EdiOancea

Closes #6

2019-03-07 16:36 UTC, lgnstn requested changes

2019-03-07 16:36 UTC, lgnstn commented on src/Components/Calculator.js
> +    if(operation !== '') {
Please add a space after `if`.

2019-03-07 16:36 UTC, lgnstn commented on src/Components/Calculator.js
> +      this.setState({ displayed:eval(`${a} ${operation} ${b}`) });
Missing space after `:`.

2019-03-11 07:56 UTC, lgnstn approved these changes

2019-03-11 08:42 UTC, EdiOancea commented
@lgnstn updated

2019-03-11 08:44 UTC, lgnstn approved these changes

2019-03-11 08:44 UTC, merged